# -- Default styles (for solo "TIP3P_1983_CHARMM" water) --
units        real
atom_style   full

# I'm not sure exactly which cutoffs distances are traditionally used in
# in the 1983 "TIP3P" model by Jorgensen model, (used by CHARMM).
# (See the Price JCP 2004 paper for a review.)
#   My first guess was this:
pair_style   lj/charmm/coul/charmm 7.5 8.0 10.0 10.5

# However, in the LAMMPS "peptide" example, they use these parameters:
# pair_style   lj/charmm/coul/long 8.0 10.0 10.0

#pair_modify  mix arithmetic  # LEAVE THIS UNSPECIFIED!
atom_style full
units           real
bond_style      harmonic
angle_style     charmm
dihedral_style  charmm
improper_style  harmonic
pair_style      lj/charmm/coul/long 8 12
pair_modify     mix arithmetic
kspace_style    pppm 1e-6
special_bonds   charmm
